<?php
session_start();
$con = null;
require ('../pdflib/fpdf.php');
require ('../DB_Connect.php');
$type = $_GET['type'];
$admin_id = $_SESSION['active_admin_name'];
$datetoday = Date("M-d-Y");

if(isset($_GET['daily'])){
    $time = '1 day';
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and DATE_FORMAT(`dateadded`,"%Y %M %d") = DATE_FORMAT(NOW(),"%Y %M %d") ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'" and DATE_FORMAT(`dateadded`,"%Y %M %d") = DATE_FORMAT(NOW(),"%Y %M %d") GROUP by name ORDER BY name, dateadded asc';
}
elseif(isset($_GET['weekly'])){
    $time = '1 week';
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and yearweek(`dateadded`) = yearweek(NOW()) ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'" and yearweek(`dateadded`) = yearweek(NOW()) GROUP by name ORDER BY name, dateadded asc';
}
elseif(isset($_GET['monthly'])){
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and MONTH(`dateadded`) = MONTH(NOW()) ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'" and MONTH(`dateadded`) = MONTH(NOW()) GROUP by name ORDER BY name, dateadded asc';
    //MONTH(`dateadded`) = MONTH(NOW())
    $time = '1 month';
}
elseif(isset($_GET['quarterly'])){
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and QUARTER(`dateadded`) = QUARTER(NOW()) ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'" and QUARTER(`dateadded`) = QUARTER(NOW()) GROUP by name ORDER BY name, dateadded asc';
    $time = '1 quarter';
}
elseif(isset($_GET['annually'])){
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and YEAR(`dateadded`) = YEAR(NOW()) ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'" and YEAR(`dateadded`) = YEAR(NOW()) GROUP by name ORDER BY name, dateadded asc';
    //YEAR(`dateadded`) = YEAR(NOW())
    $time = '1 year';
}
elseif(isset($_GET['customdate'])){
    $date = $_GET['customdate'];
    $datearr = explode(',',$date);
    $date1 = $datearr[0];
    $startdate = date("Y-m-d", strtotime($date1));
    $date2 = $datearr[1];
    $enddate = date("Y-m-d", strtotime($date2));
    $sql = 'Select * from `medreport` where `type` = "'.$type.'" and date(dateadded) BETWEEN date("'.$startdate.'") and date("'.$enddate.'") ORDER BY dateadded asc';
    $sql2 = 'Select name,SUM(stock) as stock FROM medreport where `type` = "'.$type.'"  and date(dateadded) BETWEEN date("'.$startdate.'") and date("'.$enddate.'") GROUP by name ORDER BY name, dateadded asc';
}
$pdfquery = $sql;
$sumpdfquery = $sql2;
$record = mysqli_query($con,$pdfquery);
if($type == 'Medicine'){
    $type = "Medicine Released";
}
elseif($type == 'Vaccine'){
    $type = "Vaccine Released";
}
elseif($type == "Add"){
    $type = "Added Medicines";
}
elseif($type == "Update"){
    $type = "Updated Stocks";
}
elseif($type == "Delete"){
    $type = "Deleted Medicine";
}
class PDF extends FPDF{
    function Header()
    {
        $this->Image('HIS logo blue.png',10,6,50);
        $this->SetFont('Arial','B',15);
        $this->Cell(80);
        $this->Cell(30,15,'Sto. Rosario Rural Health Center');
        $this->Ln(37);
    }
    // Page footer
    function Footer()
    {
        $datetoday = Date("M-d-Y");
        // Position at 1.5 cm from bottom
        $this->SetY(-15);
        // Arial italic 8
        $this->SetFont('Arial','I',8);
        // Page number
        $this->Cell(0,10,'Date Created: '.$datetoday,0,0,'L');
        $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'R');

        if($this->isFinished){
            $this->SetY(-40);
            $admin_id = $_SESSION['active_admin_name'];
            $this->SetFont('Arial','I',12);
            $this->MultiCell(0,10,"\nGenerated by: ".$admin_id,0,'R');
        }

    }
    function myCell($w,$h,$x,$t){
        $height = $h/3;
        $first = $height+2;
        $second = $height+$height+$height+3;
        $len = strlen($t);
        if($len>25){
            $txt = str_split($t,25);
            $this->SetX($x);
            $this->Cell($w,$first,$txt[0],'','','');
            $this->SetX($x);
            $this->Cell($w,$second,$txt[1],'','','');
            $this->SetX($x);
            $this->Cell($w,$h,'','T',0,'L',0);
        }
        else{
            $this->SetX($x);
            $this->Cell($w,$h,$t,'T');
        }
    }
}
$pdf = new PDF('p');
$pdf->AliasNbPages();
$pdf->isFinished = false;
$pdf->AddPage();
$pdf->SetFont('Arial','B',12);
$pdf->Text(10,40,"Medicine Reports (".$type.")");
$pdf->Ln(10);
//$pdf->AddPage();
//$pdf->Text(170,40,"$datetoday");
$w = 50;
$h = 16;
$pdf->Cell(50,10,"Medicine ID",0,0,'L');
$pdf->Cell(50,10,"Medicine Name",0,0,'L');
$pdf->Cell(0,10,"Medicine Description",0,1,'C');
$pdf->SetFont('Arial','',10);
    while($row = mysqli_fetch_assoc($record)){
        $x = $pdf->GetX();
        $pdf->myCell($w,$h,$x,$row['id']);
        $x = $pdf->GetX();
        $pdf->myCell($w,$h,$x,$row['name']." (".$row['dosage'].")");
        $pdf->MultiCell(0,5,"Category: ".$row['category']."\nStocks: ".$row['stock'] ."\nMFG-Date & EXP-Date: " .$row['mfgdate'] ."-". $row['expdate']. "\nDate Occured: ".$row['dateadded'],"LT",'L');
        $pdf->isFinished = false;
    }
$pdf->Ln(10);

$pdf->isFinished = true;
$pdf->Output('D','Report-'.$type.'-'.$datetoday.'.pdf');
